
// This file is "main.dart"
import 'package:freezed_annotation/freezed_annotation.dart';

// required: associates our `main.dart` with the code generated by Freezed
part 'reading.freezed.dart';
// optional: Since our Person class is serializable, we must add this line.
// But if Person was not serializable, we could skip it.
part 'reading.g.dart';

@freezed
class Reading with _$Reading {
  const factory Reading({
    required double reading,
    required String mealType,
    required String dateTime,
  }) = _Reading;

  factory Reading.fromJson(Map<String, Object?> json)
  => _$ReadingFromJson(json);
}